sudo: false
language: scala

scala:
  - 2.12.3
  - 2.11.11

before_cache:
  - find $HOME/.sbt -name "*.lock" -type f -delete
  - find $HOME/.ivy2/cache -name "ivydata-*.properties" -type f -delete

cache:
  directories:
    - $HOME/.ivy2/cache
    - $HOME/.coursier/cache
    - $HOME/.sbt

jdk:
  - oraclejdk8

script:
  - sbt ++$TRAVIS_SCALA_VERSION test
